export default [
    { text: '主页', link: '/' },
    { text: '设定集收录',
      items: [
        { text: 'StarCraftII', link: '/StarCraft/官方美术设定集.md', target: '_self', },
        { text: 'WorldOfVaira', link: '/WorldofVaira/', target: '_self', },
      ],
    },
    { text: '其他',
      items: [
        { text: 'SCP', link: 'https://hog-starwatch.github.io/SCP/', target: '_self', },
        { text: 'Novel', link: 'https://hog-starwatch.github.io/Novel/', target: '_self', },
        { text: 'Domain', link: '/DomainIndex.md', target: '_self', },
        { text: 'RPGMaker相关', link: '/RPGMaker/', target: '_self', },
        { text: 'Windows/Office', link: '/MAS/', target: '_self', },
        { text: 'CF', link: '/CF/', target: '_self', },
        { text: 'HF-Space-AppConverter', link: '/web-tools/hf-space-app-converter.html', target: '_self', },
        { text: '排序算法可视化', link: '/web-tools/sorting_visualizer.html', target: '_self', },
        { text: '魔女之旅知识测试', link: '/games/ElenaTest.html', target: '_self', },
        { text: 'SBTI', link: 'https://何意味.de5.net/', target: '_self', },
      ],
    },
    { text: '小工具',
      items: [
        { text: 'Windows11美化(自用24H2)',
          items: [
          { text: '硬盘图标修改', link: '/Beautify/DiskIconChanger.html', target: '_self', },
          { text: 'Win11文件管理器背景', link: '/Beautify/ExplorerBg.md', target: '_self', },
          { text: 'Win11文件管理器透明', link: '/Beautify/ExplorerBlueMica.md', target: '_self', },
          ],
        },
        { text: 'TDL', link: '/TDL/', target: '_self', },
        { text: '加速键盘', link: '/KeyRate/KeyRate.md', target: '_self', },
        { text: 'CMDPack', link: '/Tools/CMDPack.md', target: '_self', },
        { text: 'DelWinDuplicateFile_ver.FK', link: '/Tools/Delete-WindowsDuplicateFiles.md', target: '_self', },
      ],
    },
    { text: '网页小工具',
      items: [
        { text: 'AURORA❤极光', link: '/AURORA/index.html', target: '_self', },
        { text: '网易云音乐.NCM', link: '/web-tools/NeteaseNCM.html', target: '_self', },
        { text: '静态HTML可视化编辑', link: '/web-tools/html-visual-editor.html', target: '_self', },
        { text: 'Binary-Waterfall', link: '/web-tools/Binary-Waterfall.html', target: '_self', },
        { text: 'HTML在线运行', link: '/web-tools/html_runner.html', target: '_self', },
        { text: 'HTML在线运行', link: '/web-tools/htmlrunner.html', target: '_self', },
        { text: 'qrcode-decoder', link: '/web-tools/qrcode-decoder.html', target: '_self', },
        { text: '从夯到拉', link: '/games/tier-list.html', target: '_self', },
        { text: '脚本执行器ProMax', link: '/web-tools/ScriptExecutor.html', target: '_self', },
        { text: 'Mp4ToWebP', link: '/web-tools/mp4-to-webp.html', target: '_self', },
        { text: 'UnicodeQQ昵称', link: '/web-tools/Unicode.html', target: '_self', },
        { text: 'File64', link: '/web-tools/File64.html', target: '_self', },
        { text: '延迟&测速', link: '/web-tools/ping-speedtest.html', target: '_self', },
        { text: 'RDAP-Whois', link: '/web-tools/RDAP-whois.html', target: '_self', },
        { text: 'Pixiv代理', link: '/apps/i.pximg/index.html', target: '_self', },
        { text: 'HTML混淆', link: '/web-tools/htmlencrypt.html', target: '_self', },
        { text: 'Github仓库探索器', link: '/apps/github-repo-explorer/index.html', target: '_self', },

        { text: '旋律生成器', link: '/web-tools/melody.html', target: '_self', },
        { text: '时钟', link: '/web-tools/clock.html', target: '_self', },
      ],
    },
    { text: '小游戏',
      items: [
        { text: 'Wordle', link: '/games/Wordle.html', target: '_self', },
        { text: '地址栏贪吃蛇-推荐无痕模式游玩;)', link: '/games/snake/index.html', target: '_self', },
        { text: 'Music-world.execute.me', link: '/games/Mili/world.execute.me.html', target: '_self', },
        { text: '扫雷', link: '/games/minesearch.html', target: '_self', },
        { text: '巴别图书馆', link: '/games/巴别图书馆.html', target: '_self', },
        { text: 'Maze', link: '/games/maze.html', target: '_self', },
        { text: '2048', link: '/games/2048.html', target: '_self', },
        { text: '俄罗斯方块', link: '/games/tetris.html', target: '_self', },
        { text: '21SpaceHuggers', link: '/games/21SpaceHuggers.html', target: '_self', },
        { text: '21SpaceHuggers-SWC', link: '/games/SpaceHuggers-SWC/index.html', target: '_self', },
        { text: '24dr1v3n-wild', link: '/games/24dr1v3n-wild.html', target: '_self', },
        { text: '24escape-from-planet-xiii', link: '/games/24escape-from-planet-xiii.html', target: '_self', },
        { text: '25clawstrike', link: '/games/25clawstrike.html', target: '_self', },
        { text: 'mitruvian-van', link: '/games/aplovestudio/mitruvian-van-18-edition/index.html', target: '_self', },
        { text: 'please-touch-tiffany', link: '/games/aplovestudio/please-touch-tiffany/index.html', target: '_self', },
        { text: 'wifes-bedroom', link: '/games/aplovestudio/wifes-bedroom/index.html', target: '_self', },
        { text: 'plapping-simulator', link: '/games/plapping-simulator/index.html', target: '_self', },
        { text: 'sakissluttystriptease', link: '/games/sakissluttystriptease/index.html', target: '_self', },
      ],
    },
];
