export default [
    { text: '主页', link: '/' },
    { text: '设定集收录',
      items: [
        { text: 'StarCraftII', link: '../../../StarCraft/官方美术设定集.md', target: '_self', },
        { text: 'WorldOfVaira', link: '../../../WorldofVaira/', target: '_self', },
      ],
    },
    { text: '其他',
      items: [
        { text: 'SCP', link: 'https://hog-starwatch.github.io/SCP/', target: '_self', },
        { text: 'Novel', link: 'https://hog-starwatch.github.io/Novel/', target: '_self', },
        { text: 'Domain', link: '../../../DomainIndex.md', target: '_self', },
      ],
    },
    { text: '小工具',
      items: [
        { text: '图片处理',
          items:[
            { text: '颜色格式转换&取色', link: '../../../颜色格式转换&取色.html', target: '_self', },
            { text: '图片像素化', link: '../../../pix.html', target: '_self', },
            { text: '二维码生成器', link: '../../../QrCode.html', target: '_self', },
            { text: '差值分离图像加密', link: '../../../差值分离图像加密.html', target: '_self', },
            { text: '幻影坦克', link: '../../../幻影坦克.html', target: '_self', },
            { text: '图种', link: '../../../imgseed.html', target: '_self', },
            { text: '文件转二维码', link: '../../../File2QRcode.html', target: '_self', },
          ],
        },
        { text: '音阶片段生成器', link: '../../../Music.html', target: '_self', },
        { text: '时钟', link: '../../../时钟.html', target: '_self', },
        { text: '时钟-配置版', link: '../../../时钟-配置版.html', target: '_self', },
        { text: '字符串处理',
          items: [
            { text: '繁简体转换', link: '../../../繁简体转换.html', target: '_self', },
            { text: '零宽隐写', link: '../../../零宽隐写.html', target: '_self', },
            { text: '加密解密', link: '../../../加密解密.html', target: '_self', },
            { text: '四位可扩展加密', link: '../../../16_21-4可扩展加密.html', target: '_self', },
            { text: '更好的十六位可扩展加密', link: '../../../better可拓展加密.html', target: '_self', },
            { text: '字符串计数工具', link: '../../../字符串计数工具.html', target: '_self', },
            { text: '文本处理单位换算', link: '../../../文本处理单位换算.html', target: '_self', },
            { text: 'Unicode字符转换', link: '../../../Unicode.html', target: '_self', },
            { text: 'URL中文字符转换', link: '../../../urlcode.html', target: '_self', },
          ],
        },
        { text: '文件处理',
          items: [
            { text: 'm3u8在线下载', link: '../../../m3u8/index.html', target: '_self', },
            { text: 'Word转MarkDown', link: '../../../word2md.html', target: '_self', },
            { text: 'PDF查看器', link: '../../../pdfviewer.html', target: '_self', },
            { text: 'Video查看器', link: '../../../video.html', target: '_self', },
            { text: '图片格式转换', link: '../../../img2img.html', target: '_self', },
            { text: '文件多合一-非压缩', link: '../../../Zip.html', target: '_self', },
            { text: '文件夹合一-非压缩', link: '../../../Zip-dir.html', target: '_self', },
          ],
        },
        { text: 'HTML相关',
          items: [
            { text: 'HTML在线运行', link: '../../../htmlrunner.html', target: '_self', },
            { text: '脚本执行器', link: '../../../脚本执行器.html', target: '_self', },
            { text: '文本转义html语法', link: '../../../txt2html.html', target: '_self', },
          ],
        },
      ],
    },
    { text: '小游戏',
      items: [
        { text: 'Wordle', link: '../../../Wordle.html', target: '_self', },
      ],
    },
    { text: '其他',
      items: [
        { text: 'RPGMaker相关', link: '../../../RPGMaker/RPGMaker_index.md', target: '_self', },
        { text: 'RPGMakerMV存档的加密解密与保护', link: '../../../RPGMaker/RPGMakerMV存档的加密解密与保护.md', target: '_self', },
      ],
    },
    
];