export default [
    { text: '主页', link: '/' },
    { text: '设定集收录',
      items: [
        { text: 'StarCraftII', link: '/StarCraft/官方美术设定集.md' },
        { text: 'WorldOfVaira', link: '/WorldofVaira/' },
      ],
    },
    { text: '其他',
      items: [
        { text: 'SCP', link: 'https://hog-starwatch.github.io/SCP/', target: '_self', },
        { text: 'Novel', link: 'https://hog-starwatch.github.io/Novel/', target: '_self', },
      ],
    },
    { text: '小工具',
      items: [
        { text: '颜色格式转换&取色', link: '../../../颜色格式转换&取色.html', target: '_self', },
        { text: '二维码生成器', link: '../../../QrCode.html', target: '_self', },
        { text: '音阶片段生成器', link: '../../../Music.html', target: '_self', },
        { text: '字符串处理',
          items: [
            { text: '繁简体转换', link: '../../../繁简体转换.html', target: '_self', },
            { text: '零宽隐写', link: '../../../零宽隐写.html', target: '_self', },
            { text: '加密解密', link: '../../../加密解密.html', target: '_self', },
            { text: '四位可扩展加密', link: '../../../16_21-4可扩展加密.html', target: '_self', },
            { text: '字符串计数工具', link: '../../../字符串计数工具.html', target: '_self', },
            { text: 'Unicode字符转换', link: '../../../Unicode.html', target: '_self', },
          ],
        },
        { text: '文件处理',
          items: [
            { text: 'Word转MarkDown', link: '../../../word2md.html', target: '_self', },
            { text: '图片格式转换', link: '../../../img2img.html', target: '_self', },
            { text: '文件多合一-非压缩', link: '../../../Zip.html', target: '_self', },
            { text: '文件夹合一-非压缩', link: '../../../Zip-dir.html', target: '_self', },
          ],
        },
        { text: 'HTML相关',
          items: [
            { text: 'HTML在线运行', link: '../../../htmlrunner.html', target: '_self', },
            { text: '脚本执行器', link: '../../../脚本执行器.html', target: '_self', },
            { text: '文本转义html语法', link: '../../../txt2html.html', target: '_self', },
          ],
        },
      ],
    },
    { text: '小游戏',
      items: [
        { text: 'Wordle', link: '../../../Wordle.html', target: '_self', },
        { text: '井字棋', link: '../../../井字棋.html', target: '_self', },
        { text: '五子棋', link: '../../../五子棋.html', target: '_self', },
        { text: '打砖块', link: '../../../打砖块.html', target: '_self', },
        { text: '贪吃蛇', link: '../../../贪吃蛇.html', target: '_self', },
        { text: '猜数字', link: '../../../猜数字.html', target: '_self', },
      ],
    },
    { text: '其他',
      items: [
        { text: 'RPGMaker相关', link: '/RPGMaker/RPGMaker_index.md', target: '_self', },
        { text: 'RPGMakerMV存档的加密解密与保护', link: '/RPGMaker/RPGMakerMV存档的加密解密与保护.md' },
      ],
    },
    
];